TOTAL_DATA_URL = 'https://disease.sh/v3/covid-19/all'
TOTAL_COUNTRY_WISE_DATA_URL = 'https://disease.sh/v3/covid-19/countries'
TOTAL_DATA_IN_DT_URL = 'https://disease.sh/v3/covid-19/historical/all?lastdays=all'
COUNTRY_DATA_URL = 'https://disease.sh/v3/covid-19/countries/{}'
COUNTRY_DATA_IN_DT_URL = 'https://disease.sh/v3/covid-19/historical/{}?lastdays=all'
STATE_WISE_DATA_URL = 'https://covidindia.org/'
# FIREBASE_ADMIN_SDK_CREDENTIAL_PATH = 'corona-tracker-fcbf9-firebase-adminsdk-credential.json'
apiKey = 'AIzaSyAXYXalGdV43D8npQwDfp6RsrU3gNi7XNc'
authDomain = 'corona-tracker-fcbf9.firebaseapp.com'
databaseURL = 'https://corona-tracker-fcbf9.firebaseio.com/'
projectId = 'covid19-news-9d60d'
storageBucket = 'corona-tracker-fcbf9.appspot.com'
messagingSenderId = '1084177938782'
TABLE_NAME1 ='articles'
TABLE_NAME2 = 'admin'
SERVER_FILES_PATH = 'static/SERVER_FILES/img/'
